/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import Modelo.Cliente;
import java.util.ArrayList;

/**
 *
 * @author daw-B
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
       vClientes= new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1Datos = new javax.swing.JPanel();
        jLabel1Nombre = new javax.swing.JLabel();
        jLabel2Ape1 = new javax.swing.JLabel();
        jLabel3Ape2 = new javax.swing.JLabel();
        jTextField1Nombre = new javax.swing.JTextField();
        jTextField2Ape1 = new javax.swing.JTextField();
        jTextField3Ape2 = new javax.swing.JTextField();
        jLabel1Estado = new javax.swing.JLabel();
        jComboBox1Estado = new javax.swing.JComboBox<>();
        jLabel1Sexo = new javax.swing.JLabel();
        jRadioButton1Mas = new javax.swing.JRadioButton();
        jRadioButton2Fem = new javax.swing.JRadioButton();
        jLabel1Edad = new javax.swing.JLabel();
        jTextField1Edad = new javax.swing.JTextField();
        jButton1Guardar = new javax.swing.JButton();
        jButton1Salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(788, 590));

        jPanel1Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1Nombre.setText("Nombre:");

        jLabel2Ape1.setText("Primer apellido:");

        jLabel3Ape2.setText("Segundo apellido:");

        jLabel1Estado.setText("Estado civil:");

        jComboBox1Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo" }));

        jLabel1Sexo.setText("Sexo:");

        buttonGroup1.add(jRadioButton1Mas);
        jRadioButton1Mas.setText("Masculino");

        buttonGroup1.add(jRadioButton2Fem);
        jRadioButton2Fem.setText("Femenino");
        jRadioButton2Fem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1Edad.setText("Edad:");

        javax.swing.GroupLayout jPanel1DatosLayout = new javax.swing.GroupLayout(jPanel1Datos);
        jPanel1Datos.setLayout(jPanel1DatosLayout);
        jPanel1DatosLayout.setHorizontalGroup(
            jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1Edad)
                    .addComponent(jLabel1Sexo)
                    .addComponent(jLabel2Ape1)
                    .addComponent(jLabel3Ape2)
                    .addComponent(jLabel1Nombre)
                    .addComponent(jLabel1Estado))
                .addGap(32, 32, 32)
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1Nombre)
                        .addComponent(jTextField2Ape1)
                        .addComponent(jTextField3Ape2)
                        .addComponent(jComboBox1Estado, 0, 235, Short.MAX_VALUE))
                    .addGroup(jPanel1DatosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton1Mas)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2Fem))
                    .addComponent(jTextField1Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1DatosLayout.setVerticalGroup(
            jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Nombre)
                    .addComponent(jTextField1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Ape1)
                    .addComponent(jTextField2Ape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3Ape2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3Ape2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Estado)
                    .addComponent(jComboBox1Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Sexo)
                    .addComponent(jRadioButton1Mas)
                    .addComponent(jRadioButton2Fem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Edad)
                    .addComponent(jTextField1Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1Guardar.setBackground(new java.awt.Color(255, 255, 255));
        jButton1Guardar.setText("Guardar");
        jButton1Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1GuardarMouseClicked(evt);
            }
        });

        jButton1Salir.setBackground(new java.awt.Color(255, 255, 255));
        jButton1Salir.setText("Salir");
        jButton1Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1SalirMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1Texto.setColumns(20);
        jTextArea1Texto.setRows(5);
        jTextArea1Texto.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1Texto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jButton1Guardar)
                .addGap(18, 18, 18)
                .addComponent(jButton1Salir)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Salir)
                    .addComponent(jButton1Guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Datos usuario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1SalirMouseClicked

    private void jButton1GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1GuardarMouseClicked
        String nombre=jTextField1Nombre.getText();
        String ape1=jTextField2Ape1.getText();
        String ape2=jTextField3Ape2.getText();
        String estado = (String)jComboBox1Estado.getSelectedItem();
        String edad=jTextField1Edad.getText();
        String sexo="";
       
        if(jRadioButton1Mas.isSelected()){
            sexo="Masculino";            
        }else{
            sexo="Femenino";
        }
        
        //jTextArea1Texto.setText(nombre + " " + ape1 + " " + ape2 + " " + estado + " " + edad + " " + sexo);

        Cliente n = new Cliente(nombre, ape1, ape2, estado, sexo, Integer.parseInt(edad));
      
        jTextArea1Texto.setText(n.toString());
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1GuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    private ArrayList<String> vClientes;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1Guardar;
    private javax.swing.JButton jButton1Salir;
    private javax.swing.JComboBox<String> jComboBox1Estado;
    private javax.swing.JLabel jLabel1Edad;
    private javax.swing.JLabel jLabel1Estado;
    private javax.swing.JLabel jLabel1Nombre;
    private javax.swing.JLabel jLabel1Sexo;
    private javax.swing.JLabel jLabel2Ape1;
    private javax.swing.JLabel jLabel3Ape2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1Datos;
    private javax.swing.JRadioButton jRadioButton1Mas;
    private javax.swing.JRadioButton jRadioButton2Fem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Texto;
    private javax.swing.JTextField jTextField1Edad;
    private javax.swing.JTextField jTextField1Nombre;
    private javax.swing.JTextField jTextField2Ape1;
    private javax.swing.JTextField jTextField3Ape2;
    // End of variables declaration//GEN-END:variables
}
